### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.view.ViewGroup.dispatchTouchEvent(android.view.MotionEvent)' on a null object reference

### ISSUE THREAD

**Issue by ngokhongkn** [FolioReader/FolioReader-Android#239]
07-10 08:43:55.768 32514-32514/de.zweidenker.rheinwerk_reader E/AndroidRuntime: FATAL EXCEPTION: main
    Process: de.zweidenker.rheinwerk_reader, PID: 32514
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.view.ViewGroup.dispatchTouchEvent(android.view.MotionEvent)' on a null object reference
        at com.folioreader.view.FolioWebView.computeHorizontalScroll(FolioWebView.java:121)
        at com.folioreader.view.FolioWebView.onTouchEvent(FolioWebView.java:108)
        at android.view.View.dispatchTouchEvent(View.java:10779)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2859)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2535)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2492)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2492)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2492)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2492)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2492)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2492)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2492)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2492)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2492)
        at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:582)
        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1885)
        at android.app.Activity.dispatchTouchEvent(Activity.java:3240)
        at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:71)

**Comment by javavirys** [comment]
Add to FolioWebView.java  if (webViewPager! = Null) webViewPager.dispatchTouchEvent (event);

**Comment by hrishikesh-kadam** [comment]
@ngokhongkn Can you please share EPUB file with us so that we can investigate?

@javavirys the solution you proposed would not make the Horizontal scrolling feature work. It would be helpful if you can share EPUB file with us.

This generally happens when JS Horizontal pagination code doesn't give callback to Java code in `FolioWebView.setHorizontalPageCount(int)`

**Comment by javavirys** [comment]
Here's the epub
[pub.zip](https://github.com/FolioReader/FolioReader-Android/files/2186157/pub.zip)

**Comment by hrishikesh-kadam** [comment]
@javavirys I am unable to reproduce the issue.
Can you please give me exact steps?

**Comment by ngokhongkn** [comment]
Hi everybody
When I switch very fast, this error occurs.
In my project, I use folioreader to open each html page and not use it to open the epub.
thanks everyone. I fixed it by check null

**Comment by hrishikesh-kadam** [comment]
@mahavir155 I think this bug still exists due to the limitation of nanohttpd. Fast swiping between chapters leads to some connection problem between client and server.

Let's keep it open.
